// Test-only fixture: emoji_sequence -> answer for every LIVE global word in
// the DB (mirrors 20260818091446_realtime_and_seed.sql,
// 20260819040729_seed_more_words.sql, and
// 20260821173314_seed_country_and_more_words.sql, with the emoji-collision
// fix from 20260821173429_fix_dark_knight_emoji_collision.sql already
// applied). No Edge Function imports this at runtime — `words.answer` is
// never client-readable by design (CLAUDE.md rule 1), so integration tests
// that need to submit a *correct* guess have nowhere else to get the answer
// from. This mirrors the seed data verbatim; it is not a live secret, the
// same way guess.test.deno.ts's own SEEDED_ANSWERS list isn't — both are
// copies of what's already sitting in a committed migration file. Keep in
// sync by hand if the seed data changes (a mismatch throws loudly in
// answerFor/difficultyFor rather than failing a test confusingly later).

export const SEED_WORDS: Record<string, string> = {
  // Country
  "🦘🏄": "australia",
  "🎻🏔️🍰": "austria",
  "🐅🌊🕌": "bangladesh",
  "🍫🧇🚲": "belgium",
  "🍁🏒": "canada",
  "🌶️🏔️🍷": "chile",
  "🐼🥢": "china",
  "🫒🏛️🌊": "greece",
  "🌶️🍲🏰": "hungary",
  "🌋❄️♨️": "iceland",
  "🐘🕌🍛": "india",
  "🎤📱🥢": "japan",
  "🌮🌵": "mexico",
  "🐫🏜️🧿": "morocco",
  "🏔️🙏🚩": "nepal",
  "🐑🥝": "new zealand",
  "🏏🧕🕌": "pakistan",
  "🐻❄️🎻": "russia",
  "🐪🛢️🏜️": "saudi arabia",
  "🦁🍷🏞️": "south africa",
  "🐂💃🥘": "spain",
  "🍛🐘🏖️": "sri lanka",
  "🛋️📦❄️": "sweden",
  "🏔️🍫🧀": "switzerland",
  "🏙️🛢️🌆": "united arab emirates",
  "☕👑🌂": "united kingdom",
  "🗽🍔": "united states",

  // Food
  "🍏🥧": "apple pie",
  "🍔🧀🥓": "bacon cheeseburger",
  "🍲🥔🐄": "beef stew",
  "🥗🧀🥖🥬": "caesar salad",
  "🐔🍛🌶️": "chicken curry",
  "🌽🧈🔥": "corn on the cob",
  "🥟🥢": "dumplings",
  "🍲🐟🌶️": "fish stew",
  "🍞🧀🔥": "grilled cheese sandwich",
  "🐟🍋🌿": "grilled fish",
  "🦞🧈": "lobster",
  "🍝🧀": "mac and cheese",
  "🍡🌸": "mochi",
  "🌶️🧀🌽": "nachos",
  "🍚🥢🍙": "onigiri",
  "🦪🍋": "oysters",
  "🥙🧆🥬": "shawarma",
  "🥩🧄🧈": "steak",
  "🦃🥔🌽": "thanksgiving",
  "🍕🍄🧅": "veggie pizza",

  // Movies
  "🐜🔍": "a bug's life",
  "🧞‍♂️🪔": "aladdin",
  "🕰️🐇🕳️": "alice in wonderland",
  "🕰️🚗⚡": "back to the future",
  "🦇🃏": "batman",
  "🌹👹🏰": "beauty and the beast",
  "🐝🍯👔": "bee movie",
  "🦸‍♂️🛡️": "captain america",
  "🚗⚡🏁": "cars",
  "🍫🏭": "charlie and the chocolate factory",
  "👠🎃🕛": "cinderella",
  "🧛🩸": "dracula",
  "👽🚲🌕": "e.t.",
  "🚗🏎️💨": "fast and furious",
  "🐠🔍": "finding nemo",
  "⛄👸❄️": "frozen",
  "👻🔫": "ghostbusters",
  "🐧❄️💃": "happy feet",
  "🧙⚡👓": "harry potter",
  "🧙‍♀️🎃🕯️": "hocus pocus",
  "🐉🥚🔥": "how to train your dragon",
  "🧠🔄💤": "inception",
  "🧑‍🚀🪐⏳": "interstellar",
  "🤡🎈🔴": "it",
  "🦈🌊": "jaws",
  "🎭🃏": "joker",
  "🦖🏝️": "jurassic park",
  "🦍🏙️": "king kong",
  "🐼🥋": "kung fu panda",
  "🦁🦒🦓🏝️": "madagascar",
  "🕶️👽🔫": "men in black",
  "🐳🎣": "moby dick",
  "🦑🤖💥": "pacific rim",
  "🧚‍♀️🏴‍☠️⏰": "peter pan",
  "🏴‍☠️🦜⚓": "pirates of the caribbean",
  "🚂🎅❄️": "polar express",
  "🐭🧑‍🍳🍅": "ratatouille",
  "🏹🌳🤠": "robin hood",
  "🥊🏙️🏆": "rocky",
  "🎸🏫": "school of rock",
  "🕵️‍♂️🔍👓": "sherlock holmes",
  "👹🧅": "shrek",
  "🍎🪞👸": "snow white",
  "🐒🚀🌕": "space chimps",
  "🕷️👨": "spider-man",
  "⭐⚔️": "star wars",
  "🚕💛🔫": "taxi driver",
  "🐺🏀": "teen wolf",
  "🦇🌃": "the dark knight",
  "🏹👧🔥": "the hunger games",
  "🦍💚⚡": "the incredible hulk",
  "🦁👑": "the lion king",
  "🧜‍♀️🐚": "the little mermaid",
  "🧙‍♂️💍🌋": "the lord of the rings",
  "🕶️💊": "the matrix",
  "🌪️🏠🧙": "the wizard of oz",
  "⚡🔨": "thor",
  "🚢🧊💔": "titanic",
  "🐭🧀🐱": "tom and jerry",
  "🤠🚀🧸": "toy story",
  "🧛‍♂️🐺❤️": "twilight",
  "🏠🎈👴": "up",
  "🖤👅👹": "venom",
  "🤖❤️🌱": "wall-e",
  "🐴⚔️🌾": "war horse",
  "🥁🎓": "whiplash",
  "🧙‍♀️💚": "wicked",
  "🎩🍫🏭": "willy wonka",
  "🦸‍♀️⚔️🛡️": "wonder woman",
  "🧟‍♂️🌆": "world war z",
  "🧟‍♀️📚🔫": "zombieland",
  "🐆🏃‍♀️🌆": "zootopia",

  // Things
  "🕰️🔔": "alarm clock",
  "🧊🥶🐻‍❄️": "arctic",
  "🪐🔭": "astronomy",
  "🏝️🦜": "bahamas",
  "🧬🔬": "biotech",
  "🎈🎂🎉": "birthday party",
  "🪃🦘": "boomerang",
  "🎳🎯": "bowling",
  "🦷😬": "braces",
  "🧦🎁": "christmas stocking",
  "⏰🐦": "early bird",
  "🌡️🤒": "fever",
  "🧯🔥": "fire extinguisher",
  "🪜🧑‍🚒": "fire fighter",
  "🪦⚰️": "funeral",
  "🧊🏔️": "glacier",
  "🍬🎃": "halloween",
  "🕸️🕷️🏚️": "haunted house",
  "🐝🍯": "honeycomb",
  "🐛🦋": "metamorphosis",
  "🪤🧀": "mousetrap",
  "🦉🌙📚": "night owl",
  "🏓🏓": "ping pong",
  "🐝🌼": "pollination",
  "🧜‍♂️🔱": "poseidon",
  "🕳️🐰": "rabbit hole",
  "🧗‍♀️🪢": "rock climbing",
  "🐫💧": "sahara desert",
  "🪒🧔": "shaving",
  "🎿❄️": "skiing",
  "🪂✈️": "skydiving",
  "🏂❄️": "snowboarding",
  "🧴🧼": "soap",
  "🧦👃": "stinky socks",
  "☀️🏖️🍦": "summer vacation",
  "🐢🐇🏁": "the tortoise and the hare",
  "🦷🧚": "tooth fairy",
  "🧭🗺️": "treasure map",
  "🌕🐺": "werewolf",
  "🌠🙏": "wishing star",
};

/** Throws rather than returning undefined — a test that can't find the
 * answer for an on-screen emoji sequence has a stale fixture, and silently
 * guessing wrong would fail confusingly three steps later instead of here. */
export function answerFor(emojiSequence: string): string {
  const answer = SEED_WORDS[emojiSequence];
  if (!answer) {
    throw new Error(
      `seed-words fixture has no answer for "${emojiSequence}" — the seed migrations changed and this file needs updating.`,
    );
  }
  return answer;
}

/** `words.difficulty` mirrored the same way SEED_WORDS mirrors `answer` —
 * not a runtime secret (only `answer` is RLS-hidden from clients), just data
 * a test can't otherwise read back without a service-role key. Keep in sync
 * by hand alongside SEED_WORDS if the seed data changes. */
export const SEED_WORD_DIFFICULTY: Record<string, "easy" | "medium" | "hard"> = {
  // Country
  "🦘🏄": "easy",
  "🎻🏔️🍰": "hard",
  "🐅🌊🕌": "hard",
  "🍫🧇🚲": "hard",
  "🍁🏒": "easy",
  "🌶️🏔️🍷": "hard",
  "🐼🥢": "easy",
  "🫒🏛️🌊": "medium",
  "🌶️🍲🏰": "hard",
  "🌋❄️♨️": "medium",
  "🐘🕌🍛": "medium",
  "🎤📱🥢": "medium",
  "🌮🌵": "easy",
  "🐫🏜️🧿": "hard",
  "🏔️🙏🚩": "hard",
  "🐑🥝": "medium",
  "🏏🧕🕌": "hard",
  "🐻❄️🎻": "medium",
  "🐪🛢️🏜️": "hard",
  "🦁🍷🏞️": "hard",
  "🐂💃🥘": "medium",
  "🍛🐘🏖️": "hard",
  "🛋️📦❄️": "hard",
  "🏔️🍫🧀": "medium",
  "🏙️🛢️🌆": "hard",
  "☕👑🌂": "medium",
  "🗽🍔": "easy",

  // Food
  "🍏🥧": "easy",
  "🍔🧀🥓": "easy",
  "🍲🥔🐄": "medium",
  "🥗🧀🥖🥬": "medium",
  "🐔🍛🌶️": "medium",
  "🌽🧈🔥": "easy",
  "🥟🥢": "easy",
  "🍲🐟🌶️": "medium",
  "🍞🧀🔥": "easy",
  "🐟🍋🌿": "medium",
  "🦞🧈": "medium",
  "🍝🧀": "easy",
  "🍡🌸": "hard",
  "🌶️🧀🌽": "medium",
  "🍚🥢🍙": "medium",
  "🦪🍋": "medium",
  "🥙🧆🥬": "hard",
  "🥩🧄🧈": "medium",
  "🦃🥔🌽": "medium",
  "🍕🍄🧅": "easy",

  // Movies
  "🐜🔍": "medium",
  "🧞‍♂️🪔": "easy",
  "🕰️🐇🕳️": "medium",
  "🕰️🚗⚡": "medium",
  "🦇🃏": "easy",
  "🌹👹🏰": "medium",
  "🐝🍯👔": "easy",
  "🦸‍♂️🛡️": "easy",
  "🚗⚡🏁": "easy",
  "🍫🏭": "medium",
  "👠🎃🕛": "easy",
  "🧛🩸": "medium",
  "👽🚲🌕": "medium",
  "🚗🏎️💨": "medium",
  "🐠🔍": "easy",
  "⛄👸❄️": "easy",
  "👻🔫": "medium",
  "🐧❄️💃": "medium",
  "🧙⚡👓": "easy",
  "🧙‍♀️🎃🕯️": "medium",
  "🐉🥚🔥": "medium",
  "🧠🔄💤": "hard",
  "🧑‍🚀🪐⏳": "medium",
  "🤡🎈🔴": "medium",
  "🦈🌊": "medium",
  "🎭🃏": "medium",
  "🦖🏝️": "easy",
  "🦍🏙️": "medium",
  "🐼🥋": "easy",
  "🦁🦒🦓🏝️": "medium",
  "🕶️👽🔫": "easy",
  "🐳🎣": "hard",
  "🦑🤖💥": "hard",
  "🧚‍♀️🏴‍☠️⏰": "medium",
  "🏴‍☠️🦜⚓": "medium",
  "🚂🎅❄️": "medium",
  "🐭🧑‍🍳🍅": "medium",
  "🏹🌳🤠": "medium",
  "🥊🏙️🏆": "medium",
  "🎸🏫": "medium",
  "🕵️‍♂️🔍👓": "medium",
  "👹🧅": "medium",
  "🍎🪞👸": "medium",
  "🐒🚀🌕": "hard",
  "🕷️👨": "easy",
  "⭐⚔️": "easy",
  "🚕💛🔫": "hard",
  "🐺🏀": "hard",
  "🦇🌃": "medium",
  "🏹👧🔥": "medium",
  "🦍💚⚡": "medium",
  "🦁👑": "easy",
  "🧜‍♀️🐚": "easy",
  "🧙‍♂️💍🌋": "medium",
  "🕶️💊": "medium",
  "🌪️🏠🧙": "medium",
  "⚡🔨": "easy",
  "🚢🧊💔": "easy",
  "🐭🧀🐱": "easy",
  "🤠🚀🧸": "easy",
  "🧛‍♂️🐺❤️": "medium",
  "🏠🎈👴": "medium",
  "🖤👅👹": "medium",
  "🤖❤️🌱": "medium",
  "🐴⚔️🌾": "hard",
  "🥁🎓": "hard",
  "🧙‍♀️💚": "medium",
  "🎩🍫🏭": "medium",
  "🦸‍♀️⚔️🛡️": "easy",
  "🧟‍♂️🌆": "medium",
  "🧟‍♀️📚🔫": "hard",
  "🐆🏃‍♀️🌆": "medium",

  // Things
  "🕰️🔔": "easy",
  "🧊🥶🐻‍❄️": "medium",
  "🪐🔭": "medium",
  "🏝️🦜": "easy",
  "🧬🔬": "medium",
  "🎈🎂🎉": "easy",
  "🪃🦘": "medium",
  "🎳🎯": "medium",
  "🦷😬": "medium",
  "🧦🎁": "medium",
  "⏰🐦": "medium",
  "🌡️🤒": "easy",
  "🧯🔥": "easy",
  "🪜🧑‍🚒": "hard",
  "🪦⚰️": "medium",
  "🧊🏔️": "medium",
  "🍬🎃": "easy",
  "🕸️🕷️🏚️": "medium",
  "🐝🍯": "easy",
  "🐛🦋": "medium",
  "🪤🧀": "easy",
  "🦉🌙📚": "medium",
  "🏓🏓": "easy",
  "🐝🌼": "medium",
  "🧜‍♂️🔱": "hard",
  "🕳️🐰": "medium",
  "🧗‍♀️🪢": "medium",
  "🐫💧": "hard",
  "🪒🧔": "medium",
  "🎿❄️": "easy",
  "🪂✈️": "easy",
  "🏂❄️": "easy",
  "🧴🧼": "easy",
  "🧦👃": "hard",
  "☀️🏖️🍦": "easy",
  "🐢🐇🏁": "medium",
  "🦷🧚": "easy",
  "🧭🗺️": "medium",
  "🌕🐺": "medium",
  "🌠🙏": "medium",
};

/** Throws for the same reason answerFor does — a stale fixture should fail
 * loudly at the lookup, not produce a silently wrong expected score. */
export function difficultyFor(emojiSequence: string): "easy" | "medium" | "hard" {
  const difficulty = SEED_WORD_DIFFICULTY[emojiSequence];
  if (!difficulty) {
    throw new Error(
      `seed-words fixture has no difficulty for "${emojiSequence}" — the seed migrations changed and this file needs updating.`,
    );
  }
  return difficulty;
}
